package com.forex.collectService.model;

public enum CurrencyPair {
    GBPUSD, NZDUSD, EURUSD, USDCAD, USDJPY, USDCHF, AUDUSD, EURGBP, EURCHF, EURJPY, GBPJPY, EURAUD, AUDJPY, CADJPY, USDHKD, EURCAD, CHFJPY, USDRUB, AUDCHF, AUDCAD, AUDNZD, EURNZD, GBPAUD, USDCNH, GBPCHF, GBPNZD, NZDCAD, NZDJPY, CADCHF, NZDCHF, BTC
}
